### PR TITLE
Update pluginList.ts

### PR DESCRIPTION
**Pull request by evelynnmimijae**
Adding web3-plugin-faucettestnet2 to the plugin list that's published on NPM Registry.

### CODE REVIEW

**Review by SantiagoDevRel — CHANGES_REQUESTED** [review]
Hi @evelynnmimijae , thanks for submiting this!
Can you please update the README.md file of the plugin with a `getting started` guide please? because when you check the [NPM package](https://www.npmjs.com/package/web3-plugin-faucettestnet2) you can only see a 'web3 plugin template' but not a guide to use the plugin or what's the plugin about
Thank you!

**Comment by evelynnmimijae** [comment]
> Hi @evelynnmimijae , thanks for submiting this! Can you please update the README.md file of the plugin with a `getting started` guide please? because when you check the [NPM package](https://www.npmjs.com/package/web3-plugin-faucettestnet2) you can only see a 'web3 plugin template' but not a guide to use the plugin or what's the plugin about Thank you!

@SantiagoDevRel Yes, I absolutely need to do that! Do I need to delete the registry or simply create an update/new version to edit the README file?

**Comment by SantiagoDevRel** [comment]
@evelynnmimijae You only need to update the README in the plugin repository, no need to edit anything else in this PR

**Comment by danforbes** [comment]
The [README](https://github.com/evelynnmimijae/web3-plugin-faucettestnet2/blob/master/README.md) actually looks good on the repository. @evelynnmimijae did you update the README _after_ you did the NPM release? If so, you may just need to do another NPM release to get NPM to pick up the README.

**Comment by evelynnmimijae** [comment]
Yes, thank you @danforbes! 

@SantiagoDevRel I updated the README.

**Comment by SantiagoDevRel** [comment]
For visibility: I just reviewed the plugin, waiting until it can work 100% before publishing it here

https://www.npmjs.com/package/web3-plugin-faucettestnet2

**Comment by evelynnmimijae** [comment]
@SantiagoDevRel, can you tell me anything about the [test file?](test/index.test.ts) I keep failing the test, which is probably why the plugin isn't working. 

Screenshot from 2024-07-18 15-51-25

**Pull request closed without merging**
